server:
  port: 8900

meli:
  api:
    url: "https://api.mercadolibre.com"

redis:
  host: 127.0.01
  port: 6379
  user:
  password:

rate:
  key-requests-today: "requests-count"
  limit: 1000000000
  path-limit: 1000000000
  auth:
    limit: 1000000000
    path-limit: 1000000000

security:
  app-key: very-hard-app-key
  app-id: very-hard-app-id
  token: jwt-token-validation