server:
  port: 8900

meli:
  api:
    url: "https://api.mercadolibre.com"

redis:
  host: 127.0.01
  port: 6379
  user:
  password:

rate:
  key-requests-today: "requests-count"
  limit: 100
  path-limit: 20
  authorized-limit: 1000