server:
  port: 8900

meli:
  api:
    url: "https://api.mercadolibre.com"

redis:
  host: 127.0.01
  port: 6379
  user:
  password:

rate:
  key-requests-today: "requests-count"
  limit: 100
  path-limit: 20
  auth:
    limit: 200
    path-limit: 40

security:
  app-key: very-hard-app-key
  app-id: very-hard-app-id
  token: jwt-token-validation